### ISSUE TITLE
Incorrect AuthError Status code

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/auth-provider#14]
After researching around a bit, it looks to me that these two status codes should be inverted:

`AuthenticationError: .unauthorized`
`AuthorizationError: .forbidden `

Rather than:

```
extension AuthenticationError: AbortError {
    public var status: Status {
        return .forbidden
    }
}
extension AuthorizationError: AbortError {
    public var status: Status {
        return .unauthorized
    }
}
```

Personally, I agree with this point of view (http://www.dirv.me/blog/2011/07/18/understanding-403-forbidden/index.html) :

>There’s a problem with 401 Unauthorized, the HTTP status code for authentication errors. And that’s just it: it’s for authentication, not authorization. Receiving a 401 response is the server telling you, “you aren’t authenticated--either not authenticated at all or authenticated incorrectly--but please reauthenticate and try again.” To help you out, it will always include a WWW-Authenticate header that describes how to authenticate.
>
>This is a response generally returned by your web server, not your web application.
>
>It’s also something very temporary; the server is asking you to try again.
>
>So, for authorization I use the 403 Forbidden response. It’s permanent, it’s tied to my application logic, and it’s a more concrete response than a 401.
>
>Receiving a 403 response is the server telling you, “I’m sorry. I know who you are--I believe who you say you are--but you just don’t have permission to access this resource. Maybe if you ask the system administrator nicely, you’ll get permission. But please don’t bother me again until your predicament changes.”
>
>In summary, a 401 Unauthorized response should be used for missing or bad authentication, and a 403 Forbidden response should be used afterwards, when the user is authenticated but isn’t authorized to perform the requested operation on the given resource.

**Comment by tanner0101** [comment]
This makes sense. Though I think this could be considered a breaking change.

@vzsg, @siemensikkema what do you think?

**Comment by siemensikkema** [comment]
@tanner0101 It can be considered a breaking change or a bug fix depending how you look at it. Would it be sufficient to move it to 1.1.0 (my preference)? Or should it move to 2.0.0?

**Comment by tanner0101** [comment]
@siemensikkema I think you're right. We should consider this a bug fix. I'll put up a PR.

**Comment by vzsg** [comment]
I don't think this is a breaking change either. And I agree with the proposition, this is the common usage of 401/403 everywhere.
