### ISSUE TITLE
Bring Back the LoginRedirectMiddleware

### ISSUE THREAD

**Issue by 0xTim** [vapor/auth-provider#16]
This seems to have disappeared at some point in the past. It should be introduced alongside the rest of the token middleware as the default way to do login for web apps

**Comment by tanner0101** [comment]
This middleware would just need to catch the unauthorized error and redirect, correct?

Something like this (some Vapor Cloud code), but with catching the error instead:

```swift
import HTTP
import Vapor

final class GuardMiddleware: Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        guard request.session?.data["user"] != nil else {
            return try Response(redirect: "/login", for: request)
        }
        
        return try next.respond(to: request)
    }
}

extension GuardMiddleware: ConfigInitializable {
    convenience init(config: Config) {
        self.init()
    }
}
```

and 

```swift
import HTTP
import Vapor

final class InverseGuardMiddleware: Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        guard request.session?.data["user"] == nil else {
            return try Response(redirect: "/", for: request)
        }
        
        return try next.respond(to: request)
    }
}

extension InverseGuardMiddleware: ConfigInitializable {
    convenience init(config: Config) {
        self.init()
    }
}
```

**Comment by 0xTim** [comment]
Yeah pretty much
A simple copy of this would work, though I'm sure I remember seeing something recently with allowed routes (like the login or reset password route being let through) but I can't find it!
https://github.com/vapor/vapor/blob/1/Sources/Auth/Authentication/LoginRedirectMiddleware.swift
