### ISSUE TITLE
RedirectType undeclared

### ISSUE THREAD

**Issue by FWAlex** [vapor/auth-provider#20]
Hello I am new to Vapor and I am trying to use the `auth-provider` but I've ran into an issue.

My package dependencies looks like this:

```
dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2, minor: 2),
        .Package(url: "https://github.com/vapor/fluent-provider.git", majorVersion: 1),
        .Package(url: "https://github.com/vapor-community/postgresql-provider.git", majorVersion: 2, minor: 0),
        .Package(url: "https://github.com/stormpath/Turnstile.git", majorVersion: 1),
        .Package(url: "https://github.com/vapor/validation-provider.git", majorVersion: 1),
        .Package(url: "https://github.com/vapor/auth-provider.git", majorVersion: 1)
    ],
```

But after I build the project I get `Use of undeclared type 'RedirectType'`. 
Does `auth-provider` require some other dependecies?

**Comment by vzsg** [comment]
No, just an update to the transitive dependencies of your project (vapor/engine needs to be at least 2.1.0 in particular). If you run `swift package update` or `vapor update`, the error should go away.

**Comment by FWAlex** [comment]
Cool! Thank you very much 👍
