### ISSUE TITLE
Allow for authenticating many types of users at once?

### ISSUE THREAD

**Issue by hhanesand** [vapor/auth-provider#4]
@tanner0101 

For my use case, I need to authenticate several different types of users, and preferably allow the user to sign in as all the different types at the same time.

However, for the current setup, this is not very easy, as the session storage name is hardcoded in `Helper` : (authAuthenticatedKey)

```swift
public func authenticate<A: Authenticatable>(_ a: A) {
    request?.storage[authAuthenticatedKey] = a
}
```

I haven't actually tested this, but I think I am correct in saying that because of this hardcoded key, several calls to `authenticate` will overwrite each other. There are checks in the provided `TokenAuthenticationMiddleware` and `PasswordAuthenticationMiddleware` to skip another authentication (line 12 and line 31 respectively), but they (should) fail to trigger because the `U` parameter will different for each call.

A proposed solution to this might to change all the hardcoded keys storage keys to be based of the type of the parameter coming into the method :
```swift
public func authenticate<A: Authenticatable>(_ a: A) {
    request?.storage[authAuthenticatedKey + String(describing: A.self)] = a
}
```

The default implementation of `SessionPersistable` will have to change to so that `sessionEntityId` becomes different for each persisted model type.

I can put together a PR if this is something we want.

**Comment by tanner0101** [comment]
@hhanesand I considered doing something like you described in the 2nd code example, but I couldn't find a compelling use case for supporting multiple logins during a single request.

Could you outline a situation where you'd need two different user types authenticated at the same time during a single request? That would help me wrap my mind around it.

Either way it looks easy to add and I don't think it will mess anything else up so I could get behind it.

**Comment by hhanesand** [comment]
Now that I'm thinking about it, there really isn't a need for this on a per request basis.
